# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(default=0)),
                ('user_id', models.CharField(default='', max_length=30)),
                ('message', models.TextField(default=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('city', models.CharField(default=None, max_length=30, null=True)),
                ('phone', models.CharField(default=None, max_length=20, null=True)),
                ('active', models.BooleanField(default=False)),
                ('tmp', models.CharField(max_length=100)),
            ],
        ),
    ]
